name: ridego_workspace
publish_to: none

environment:
  sdk: ^3.13.5

workspace:
  - apps/ridego_app
  - apps/ridego_driver_app
  - packages/ridego_core

dev_dependencies:
  melos: ^7.0.0

melos:
  scripts:
    analyze: melos exec -- flutter analyze
    test: melos exec -- flutter test